#!/usr/bin/env node

const commander = require('commander')
const hostile = require('hostile')
const chalk = require('chalk')
const error = chalk.bold.red
const info = chalk.keyword('cyan')
const success = chalk.keyword('green')
const logger = require('./src/util/logger')
const log = console.log

// Init the CLI
const program = new commander.Command()

program.command('add <host>').action(function (host) {
  hostile.set('127.0.0.1', host, function (err) {
    if (err) {
      logger.log('error', err)
      log(error(err.message))
      process.exit(1)
    } else {
      log(success('Added to hosts file successfully!'))
    }
  })
})

program.command('remove <host>').action(function (host) {
  hostile.remove('127.0.0.1', host, function (err) {
    if (err) {
      logger.log('error', err)
      log(error(err.message))
      process.exit(1)
    } else {
      log(success('Removed from hosts file successfully!'))
    }
  })
})

program.command('list').action(function () {
  const preserveFormatting = false

  hostile.get(preserveFormatting, function (err, lines) {
    if (err) {
      logger.log('error', err)
      log(error(err.message))
      process.exit(1)
    }

    lines.forEach(function (line) {
      log(info(line))
    })
  })
})

program.parse(process.argv)
